<?php

require_once __DIR__ . "/../vendor/autoload.php";

use spyfly\Plugins\Tst2Lrs\Config\ConfigCtrl;
use spyfly\Plugins\Tst2Lrs\Utils\Tst2LrsTrait;
use srag\DevTools\Tst2Lrs\DevToolsCtrl;
use srag\DIC\Tst2Lrs\DICTrait;

/**
 * Class ilTst2LrsConfigGUI
 *
 * Generated by SrPluginGenerator v2.8.1
 *
 * @author Sebastian Heiden <test2lrs@spyfly.xyz>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ilTst2LrsConfigGUI extends ilPluginConfigGUI
{

    use DICTrait;
    use Tst2LrsTrait;

    const CMD_CONFIGURE = "configure";
    const PLUGIN_CLASS_NAME = ilTst2LrsPlugin::class;


    /**
     * ilTst2LrsConfigGUI constructor
     */
    public function __construct()
    {

    }


    /**
     * @inheritDoc
     */
    public function performCommand(/*string*/ $cmd) : void
    {
        $this->setTabs();

        $next_class = self::dic()->ctrl()->getNextClass($this);

        switch (strtolower($next_class)) {
            case strtolower(ConfigCtrl::class):
                self::dic()->ctrl()->forwardCommand(new ConfigCtrl());
                break;

            default:
                $cmd = self::dic()->ctrl()->getCmd();

                switch ($cmd) {
                    case self::CMD_CONFIGURE:
                        $this->{$cmd}();
                        break;

                    default:
                        break;
                }
                break;
        }
    }


    /**
     *
     */
    protected function configure() : void
    {
        self::dic()->ctrl()->redirectByClass(ConfigCtrl::class, ConfigCtrl::CMD_CONFIGURE);
    }


    /**
     *
     */
    protected function setTabs() : void
    {
        ConfigCtrl::addTabs();

        self::dic()->locator()->addItem(ilTst2LrsPlugin::PLUGIN_NAME, self::dic()->ctrl()->getLinkTarget($this, self::CMD_CONFIGURE));
    }
}
