<?php

namespace spyfly\Plugins\Tst2Lrs\Config;

use spyfly\Plugins\Tst2Lrs\Config\Form\FormBuilder;
use spyfly\Plugins\Tst2Lrs\Utils\Tst2LrsTrait;
use ilTst2LrsPlugin;
use srag\ActiveRecordConfig\Tst2Lrs\Config\AbstractFactory;
use srag\ActiveRecordConfig\Tst2Lrs\Config\AbstractRepository;
use srag\ActiveRecordConfig\Tst2Lrs\Config\Config;

/**
 * Class Repository
 *
 * Generated by SrPluginGenerator v2.8.1
 *
 * @package spyfly\Plugins\Tst2Lrs\Config
 *
 * @author Sebastian Heiden <test2lrs@spyfly.xyz>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
final class Repository extends AbstractRepository
{

    use Tst2LrsTrait;

    const PLUGIN_CLASS_NAME = ilTst2LrsPlugin::class;
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * Repository constructor
     */
    protected function __construct()
    {
        parent::__construct();
    }


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * @inheritDoc
     *
     * @return Factory
     */
    public function factory() : AbstractFactory
    {
        return Factory::getInstance();
    }


    /**
     * @inheritDoc
     */
    protected function getFields() : array
    {
        return [
            FormBuilder::KEY_SOME => Config::TYPE_STRING
        ];
    }


    /**
     * @inheritDoc
     */
    protected function getTableName() : string
    {
        return ilTst2LrsPlugin::PLUGIN_ID . "_config";
    }
}
