<?php

namespace spyfly\Plugins\Tst2Lrs\Utils;

use spyfly\Plugins\Tst2Lrs\Repository;

/**
 * Trait Tst2LrsTrait
 *
 * Generated by SrPluginGenerator v2.8.1
 *
 * @package spyfly\Plugins\Tst2Lrs\Utils
 *
 * @author Sebastian Heiden <test2lrs@spyfly.xyz>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
trait Tst2LrsTrait
{

    /**
     * @return Repository
     */
    protected static function tst2Lrs() : Repository
    {
        return Repository::getInstance();
    }
}
