<?php

namespace spyfly\Plugins\Tst2Lrs;

use spyfly\Plugins\Tst2Lrs\Config\Repository as ConfigRepository;
use spyfly\Plugins\Tst2Lrs\Utils\Tst2LrsTrait;
use ilTst2LrsPlugin;
use srag\DIC\Tst2Lrs\DICTrait;

/**
 * Class Repository
 *
 * Generated by SrPluginGenerator v2.8.1
 *
 * @package spyfly\Plugins\Tst2Lrs
 *
 * @author Sebastian Heiden <test2lrs@spyfly.xyz>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
final class Repository
{

    use DICTrait;
    use Tst2LrsTrait;

    const PLUGIN_CLASS_NAME = ilTst2LrsPlugin::class;
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * Repository constructor
     */
    private function __construct()
    {

    }


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * @return ConfigRepository
     */
    public function config() : ConfigRepository
    {
        return ConfigRepository::getInstance();
    }


    /**
     *
     */
    public function dropTables() : void
    {
        $this->config()->dropTables();
    }


    /**
     *
     */
    public function installTables() : void
    {
        $this->config()->installTables();
    }
}
